package com.cbao.eerprospect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CivilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCivilityAllPropertiesEquals(Civility expected, Civility actual) {
        assertCivilityAutoGeneratedPropertiesEquals(expected, actual);
        assertCivilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCivilityAllUpdatablePropertiesEquals(Civility expected, Civility actual) {
        assertCivilityUpdatableFieldsEquals(expected, actual);
        assertCivilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCivilityAutoGeneratedPropertiesEquals(Civility expected, Civility actual) {
        assertThat(actual)
            .as("Verify Civility auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCivilityUpdatableFieldsEquals(Civility expected, Civility actual) {
        assertThat(actual)
            .as("Verify Civility relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCivilityUpdatableRelationshipsEquals(Civility expected, Civility actual) {
        // empty method
    }
}
