package com.cbao.eerprospect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyStatusAllPropertiesEquals(FamilyStatus expected, FamilyStatus actual) {
        assertFamilyStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyStatusAllUpdatablePropertiesEquals(FamilyStatus expected, FamilyStatus actual) {
        assertFamilyStatusUpdatableFieldsEquals(expected, actual);
        assertFamilyStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyStatusAutoGeneratedPropertiesEquals(FamilyStatus expected, FamilyStatus actual) {
        assertThat(actual)
            .as("Verify FamilyStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyStatusUpdatableFieldsEquals(FamilyStatus expected, FamilyStatus actual) {
        assertThat(actual)
            .as("Verify FamilyStatus relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyStatusUpdatableRelationshipsEquals(FamilyStatus expected, FamilyStatus actual) {
        // empty method
    }
}
