package com.cbao.eerprospect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncomePeriodicityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomePeriodicityAllPropertiesEquals(IncomePeriodicity expected, IncomePeriodicity actual) {
        assertIncomePeriodicityAutoGeneratedPropertiesEquals(expected, actual);
        assertIncomePeriodicityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomePeriodicityAllUpdatablePropertiesEquals(IncomePeriodicity expected, IncomePeriodicity actual) {
        assertIncomePeriodicityUpdatableFieldsEquals(expected, actual);
        assertIncomePeriodicityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomePeriodicityAutoGeneratedPropertiesEquals(IncomePeriodicity expected, IncomePeriodicity actual) {
        assertThat(actual)
            .as("Verify IncomePeriodicity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomePeriodicityUpdatableFieldsEquals(IncomePeriodicity expected, IncomePeriodicity actual) {
        assertThat(actual)
            .as("Verify IncomePeriodicity relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomePeriodicityUpdatableRelationshipsEquals(IncomePeriodicity expected, IncomePeriodicity actual) {
        // empty method
    }
}
