package com.cbao.eerprospect.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncomeTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeTypeAllPropertiesEquals(IncomeType expected, IncomeType actual) {
        assertIncomeTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertIncomeTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeTypeAllUpdatablePropertiesEquals(IncomeType expected, IncomeType actual) {
        assertIncomeTypeUpdatableFieldsEquals(expected, actual);
        assertIncomeTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeTypeAutoGeneratedPropertiesEquals(IncomeType expected, IncomeType actual) {
        assertThat(actual)
            .as("Verify IncomeType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeTypeUpdatableFieldsEquals(IncomeType expected, IncomeType actual) {
        assertThat(actual)
            .as("Verify IncomeType relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeTypeUpdatableRelationshipsEquals(IncomeType expected, IncomeType actual) {
        // empty method
    }
}
